// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7rDjxCJHoBklDHa5f4w5c6gtsYrktJac',
    appId: '1:631424605395:web:23f034f326e65a4aae4826',
    messagingSenderId: '631424605395',
    projectId: 'deliveryna-c0c79',
    authDomain: 'deliveryna-c0c79.firebaseapp.com',
    storageBucket: 'deliveryna-c0c79.firebasestorage.app',
    measurementId: 'G-3NBZQ5NS0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLcdtC7oKFIxDmu35vP074D5fKDHgcj8c',
    appId: '1:631424605395:android:01346b67e610a012ae4826',
    messagingSenderId: '631424605395',
    projectId: 'deliveryna-c0c79',
    storageBucket: 'deliveryna-c0c79.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrmh3CweEx_V1NZHixuB0jXmjCJKC2qQ8',
    appId: '1:631424605395:ios:e0a386234aa3456fae4826',
    messagingSenderId: '631424605395',
    projectId: 'deliveryna-c0c79',
    storageBucket: 'deliveryna-c0c79.firebasestorage.app',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrmh3CweEx_V1NZHixuB0jXmjCJKC2qQ8',
    appId: '1:631424605395:ios:e0a386234aa3456fae4826',
    messagingSenderId: '631424605395',
    projectId: 'deliveryna-c0c79',
    storageBucket: 'deliveryna-c0c79.firebasestorage.app',
    iosBundleId: 'com.example.delivery',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7rDjxCJHoBklDHa5f4w5c6gtsYrktJac',
    appId: '1:631424605395:web:784e8376bc0c74ecae4826',
    messagingSenderId: '631424605395',
    projectId: 'deliveryna-c0c79',
    authDomain: 'deliveryna-c0c79.firebaseapp.com',
    storageBucket: 'deliveryna-c0c79.firebasestorage.app',
    measurementId: 'G-EDEQTG1017',
  );
}
